kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataprocess-framework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
  storageClassName: dataprocess
