# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrapyitem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scrapyitem.proto',
  package='pgscrapyitem',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10scrapyitem.proto\x12\x0cpgscrapyitem\"\xc5\x04\n\x0cPGScrapyItem\x12\x15\n\x08\x62\x61se_url\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x35\n\npre_filter\x18\x04 \x03(\x0b\x32!.pgscrapyitem.PGScrapyItem.Filter\x12\x36\n\x0bpost_filter\x18\x05 \x03(\x0b\x32!.pgscrapyitem.PGScrapyItem.Filter\x12\x34\n\tnext_page\x18\x06 \x03(\x0b\x32!.pgscrapyitem.PGScrapyItem.Filter\x12\x30\n\x07\x65x_data\x18\n \x03(\x0b\x32\x1f.pgscrapyitem.PGScrapyItem.Data\x1a\x87\x01\n\x06\x46ilter\x12?\n\x0b\x66ilter_type\x18\x01 \x01(\x0e\x32%.pgscrapyitem.PGScrapyItem.FilterTypeH\x00\x88\x01\x01\x12\x1a\n\rfilter_string\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_filter_typeB\x10\n\x0e_filter_string\x1aj\n\x04\x44\x61ta\x12\x19\n\x0c\x65x_timestamp\x18\x07 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08raw_data\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x12\n\nex_insight\x18\t \x03(\tB\x0f\n\r_ex_timestampB\x0b\n\t_raw_data\",\n\nFilterType\x12\x07\n\x03URL\x10\x00\x12\n\n\x06\x46ILTER\x10\x01\x12\t\n\x05OTHER\x10\x02\x42\x0b\n\t_base_urlB\x05\n\x03_idb\x06proto3'
)



_PGSCRAPYITEM_FILTERTYPE = _descriptor.EnumDescriptor(
  name='FilterType',
  full_name='pgscrapyitem.PGScrapyItem.FilterType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='URL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILTER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=552,
  serialized_end=596,
)
_sym_db.RegisterEnumDescriptor(_PGSCRAPYITEM_FILTERTYPE)


_PGSCRAPYITEM_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='pgscrapyitem.PGScrapyItem.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='pgscrapyitem.PGScrapyItem.Filter.filter_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_string', full_name='pgscrapyitem.PGScrapyItem.Filter.filter_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_filter_type', full_name='pgscrapyitem.PGScrapyItem.Filter._filter_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_filter_string', full_name='pgscrapyitem.PGScrapyItem.Filter._filter_string',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=307,
  serialized_end=442,
)

_PGSCRAPYITEM_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='pgscrapyitem.PGScrapyItem.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ex_timestamp', full_name='pgscrapyitem.PGScrapyItem.Data.ex_timestamp', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='pgscrapyitem.PGScrapyItem.Data.raw_data', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ex_insight', full_name='pgscrapyitem.PGScrapyItem.Data.ex_insight', index=2,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_ex_timestamp', full_name='pgscrapyitem.PGScrapyItem.Data._ex_timestamp',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_raw_data', full_name='pgscrapyitem.PGScrapyItem.Data._raw_data',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=444,
  serialized_end=550,
)

_PGSCRAPYITEM = _descriptor.Descriptor(
  name='PGScrapyItem',
  full_name='pgscrapyitem.PGScrapyItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_url', full_name='pgscrapyitem.PGScrapyItem.base_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='pgscrapyitem.PGScrapyItem.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_filter', full_name='pgscrapyitem.PGScrapyItem.pre_filter', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='post_filter', full_name='pgscrapyitem.PGScrapyItem.post_filter', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_page', full_name='pgscrapyitem.PGScrapyItem.next_page', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ex_data', full_name='pgscrapyitem.PGScrapyItem.ex_data', index=5,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PGSCRAPYITEM_FILTER, _PGSCRAPYITEM_DATA, ],
  enum_types=[
    _PGSCRAPYITEM_FILTERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_base_url', full_name='pgscrapyitem.PGScrapyItem._base_url',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_id', full_name='pgscrapyitem.PGScrapyItem._id',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=616,
)

_PGSCRAPYITEM_FILTER.fields_by_name['filter_type'].enum_type = _PGSCRAPYITEM_FILTERTYPE
_PGSCRAPYITEM_FILTER.containing_type = _PGSCRAPYITEM
_PGSCRAPYITEM_FILTER.oneofs_by_name['_filter_type'].fields.append(
  _PGSCRAPYITEM_FILTER.fields_by_name['filter_type'])
_PGSCRAPYITEM_FILTER.fields_by_name['filter_type'].containing_oneof = _PGSCRAPYITEM_FILTER.oneofs_by_name['_filter_type']
_PGSCRAPYITEM_FILTER.oneofs_by_name['_filter_string'].fields.append(
  _PGSCRAPYITEM_FILTER.fields_by_name['filter_string'])
_PGSCRAPYITEM_FILTER.fields_by_name['filter_string'].containing_oneof = _PGSCRAPYITEM_FILTER.oneofs_by_name['_filter_string']
_PGSCRAPYITEM_DATA.containing_type = _PGSCRAPYITEM
_PGSCRAPYITEM_DATA.oneofs_by_name['_ex_timestamp'].fields.append(
  _PGSCRAPYITEM_DATA.fields_by_name['ex_timestamp'])
_PGSCRAPYITEM_DATA.fields_by_name['ex_timestamp'].containing_oneof = _PGSCRAPYITEM_DATA.oneofs_by_name['_ex_timestamp']
_PGSCRAPYITEM_DATA.oneofs_by_name['_raw_data'].fields.append(
  _PGSCRAPYITEM_DATA.fields_by_name['raw_data'])
_PGSCRAPYITEM_DATA.fields_by_name['raw_data'].containing_oneof = _PGSCRAPYITEM_DATA.oneofs_by_name['_raw_data']
_PGSCRAPYITEM.fields_by_name['pre_filter'].message_type = _PGSCRAPYITEM_FILTER
_PGSCRAPYITEM.fields_by_name['post_filter'].message_type = _PGSCRAPYITEM_FILTER
_PGSCRAPYITEM.fields_by_name['next_page'].message_type = _PGSCRAPYITEM_FILTER
_PGSCRAPYITEM.fields_by_name['ex_data'].message_type = _PGSCRAPYITEM_DATA
_PGSCRAPYITEM_FILTERTYPE.containing_type = _PGSCRAPYITEM
_PGSCRAPYITEM.oneofs_by_name['_base_url'].fields.append(
  _PGSCRAPYITEM.fields_by_name['base_url'])
_PGSCRAPYITEM.fields_by_name['base_url'].containing_oneof = _PGSCRAPYITEM.oneofs_by_name['_base_url']
_PGSCRAPYITEM.oneofs_by_name['_id'].fields.append(
  _PGSCRAPYITEM.fields_by_name['id'])
_PGSCRAPYITEM.fields_by_name['id'].containing_oneof = _PGSCRAPYITEM.oneofs_by_name['_id']
DESCRIPTOR.message_types_by_name['PGScrapyItem'] = _PGSCRAPYITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PGScrapyItem = _reflection.GeneratedProtocolMessageType('PGScrapyItem', (_message.Message,), {

  'Filter' : _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
    'DESCRIPTOR' : _PGSCRAPYITEM_FILTER,
    '__module__' : 'scrapyitem_pb2'
    # @@protoc_insertion_point(class_scope:pgscrapyitem.PGScrapyItem.Filter)
    })
  ,

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _PGSCRAPYITEM_DATA,
    '__module__' : 'scrapyitem_pb2'
    # @@protoc_insertion_point(class_scope:pgscrapyitem.PGScrapyItem.Data)
    })
  ,
  'DESCRIPTOR' : _PGSCRAPYITEM,
  '__module__' : 'scrapyitem_pb2'
  # @@protoc_insertion_point(class_scope:pgscrapyitem.PGScrapyItem)
  })
_sym_db.RegisterMessage(PGScrapyItem)
_sym_db.RegisterMessage(PGScrapyItem.Filter)
_sym_db.RegisterMessage(PGScrapyItem.Data)


# @@protoc_insertion_point(module_scope)
