# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrapyitem_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scrapyitem_test.proto',
  package='pgscrapyitem_test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15scrapyitem_test.proto\x12\x11pgscrapyitem_test\"O\n\x11PGScrapyItem_test\x12\x15\n\x08\x62\x61se_url\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_base_urlB\x05\n\x03_idb\x06proto3'
)




_PGSCRAPYITEM_TEST = _descriptor.Descriptor(
  name='PGScrapyItem_test',
  full_name='pgscrapyitem_test.PGScrapyItem_test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_url', full_name='pgscrapyitem_test.PGScrapyItem_test.base_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='pgscrapyitem_test.PGScrapyItem_test.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_base_url', full_name='pgscrapyitem_test.PGScrapyItem_test._base_url',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_id', full_name='pgscrapyitem_test.PGScrapyItem_test._id',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=44,
  serialized_end=123,
)

_PGSCRAPYITEM_TEST.oneofs_by_name['_base_url'].fields.append(
  _PGSCRAPYITEM_TEST.fields_by_name['base_url'])
_PGSCRAPYITEM_TEST.fields_by_name['base_url'].containing_oneof = _PGSCRAPYITEM_TEST.oneofs_by_name['_base_url']
_PGSCRAPYITEM_TEST.oneofs_by_name['_id'].fields.append(
  _PGSCRAPYITEM_TEST.fields_by_name['id'])
_PGSCRAPYITEM_TEST.fields_by_name['id'].containing_oneof = _PGSCRAPYITEM_TEST.oneofs_by_name['_id']
DESCRIPTOR.message_types_by_name['PGScrapyItem_test'] = _PGSCRAPYITEM_TEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PGScrapyItem_test = _reflection.GeneratedProtocolMessageType('PGScrapyItem_test', (_message.Message,), {
  'DESCRIPTOR' : _PGSCRAPYITEM_TEST,
  '__module__' : 'scrapyitem_test_pb2'
  # @@protoc_insertion_point(class_scope:pgscrapyitem_test.PGScrapyItem_test)
  })
_sym_db.RegisterMessage(PGScrapyItem_test)


# @@protoc_insertion_point(module_scope)
